version: '3'

networks:
  laravel:

services:
  site:
    build:
      context: dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: nginx
    ports:
      - "8001:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3406:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./dockerfiles/dump:/docker-entrypoint-initdb.d
#      - ./dockerfiles/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel

  php:
    build:
      context: dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: php
    volumes:
      - ./src:/var/www/html:delegated
      - ./dockerfiles/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel